-- ============================================================
-- DarkRP Custom Shipments
-- (Universal Ammo is registered in entities.lua)
-- ============================================================
