if SERVER then return end
zlt = zlt or {}

/*

    Recomments certain imgur ids if they match the typed input
    Currently only works for PrizeType[WEAPON] Class

*/

// Creates a list of possible prize inputs which are linked to imgur ids
zlt.InputToImgur = {}
local function AddImgurLink(s_input,s_imgurid) zlt.InputToImgur[s_input] = s_imgurid end
AddImgurLink("csgo_bayonet","IFTfaSQ")
AddImgurLink("csgo_bayonet_autotronic","y0fyJsV")
AddImgurLink("csgo_bayonet_black_laminate","gZwV75K")
AddImgurLink("csgo_bayonet_bluesteel","VPHqNty")
AddImgurLink("csgo_bayonet_boreal","zjbDQ8Q")
AddImgurLink("csgo_bayonet_bright_water","2KKhxXn")
AddImgurLink("csgo_bayonet_case","JFaFRRP")
AddImgurLink("csgo_bayonet_crimsonwebs","X9dxK4B")
AddImgurLink("csgo_bayonet_damascus","NGpFA9W")
AddImgurLink("csgo_bayonet_fade","SlNXtMB")
AddImgurLink("csgo_bayonet_ddpat","NqzzrBR")
AddImgurLink("csgo_bayonet_freehand","iYBrWjk")
AddImgurLink("csgo_bayonet_gamma_doppler","ACZCbmD")
AddImgurLink("csgo_bayonet_lore","vaeN1Fy")
AddImgurLink("csgo_bayonet_marblefade","PgfkfxI")
AddImgurLink("csgo_bayonet_night","Pea1B6g")
AddImgurLink("csgo_bayonet_rustcoat","42hkcrB")
AddImgurLink("csgo_bayonet_slaughter","5zbIJc4")
AddImgurLink("csgo_bayonet_tiger","q4HyO4h")
AddImgurLink("csgo_bayonet_ultraviolet","TfwQs5i")

AddImgurLink("csgo_bowie","XInbHC3")
AddImgurLink("csgo_bowie_bluesteel","OTVdMu5")
AddImgurLink("csgo_bowie_boreal","8keK6dT")
AddImgurLink("csgo_bowie_bright_water","ak6tRCi")
AddImgurLink("csgo_bowie_case","C3Osxou")
AddImgurLink("csgo_bowie_crimsonwebs","g0ZczxG")
AddImgurLink("csgo_bowie_damascus","tK4NG2F")
AddImgurLink("csgo_bowie_fade","JORqHX0")
AddImgurLink("csgo_bowie_ddpat","rCNAjF6")
AddImgurLink("csgo_bowie_freehand","6Z59OfJ")
AddImgurLink("csgo_bowie_gamma_doppler","FpX21lJ")
AddImgurLink("csgo_bowie_marblefade","M7n9r3g")
AddImgurLink("csgo_bowie_night","NKgxbyP")
AddImgurLink("csgo_bowie_rustcoat","F1FU25o")
AddImgurLink("csgo_bowie_slaughter","2DkYy5o")
AddImgurLink("csgo_bowie_tiger","Qqbj4y4")
AddImgurLink("csgo_bowie_ultraviolet","MZSYswm")

AddImgurLink("csgo_butterfly","WWq3TA9")
AddImgurLink("csgo_butterfly_bluesteel","68puhcH")
AddImgurLink("csgo_butterfly_boreal","lXjGotH")
AddImgurLink("csgo_butterfly_bright_water","3G8lNEh")
AddImgurLink("csgo_butterfly_case","KbAQZYD")
AddImgurLink("csgo_butterfly_crimsonwebs","hXrRgBp")
AddImgurLink("csgo_butterfly_damascus","f2UpKfZ")
AddImgurLink("csgo_butterfly_fade","9Cizhtd")
AddImgurLink("csgo_butterfly_ddpat","gwJuWRq")
AddImgurLink("csgo_butterfly_freehand","0OHWkBX")
AddImgurLink("csgo_butterfly_gamma_doppler","dvZVbu9")
AddImgurLink("csgo_butterfly_marblefade","WNxKt82")
AddImgurLink("csgo_butterfly_night","NM7naHe")
AddImgurLink("csgo_butterfly_rustcoat","GeV6aJk")
AddImgurLink("csgo_butterfly_slaughter","qJehV8F")
AddImgurLink("csgo_butterfly_tiger","bAaoRrR")
AddImgurLink("csgo_butterfly_ultraviolet","eiJH2zb")

AddImgurLink("csgo_daggers","mwIWxDi")
AddImgurLink("csgo_daggers_bluesteel","pmk2n90")
AddImgurLink("csgo_daggers_boreal","ip1tSMt")
AddImgurLink("csgo_daggers_bright_water","R2CCTcz")
AddImgurLink("csgo_daggers_case","dk7oQoj")
AddImgurLink("csgo_daggers_webs","5Ba1VWL")
AddImgurLink("csgo_daggers_damascus","J9nd0jQ")
AddImgurLink("csgo_daggers_fade","ltxNty8")
AddImgurLink("csgo_daggers_ddpat","V0iqGf7")
AddImgurLink("csgo_daggers_freehand","MdrmuYt")
AddImgurLink("csgo_daggers_gamma_doppler","t9xFQoN")
AddImgurLink("csgo_daggers_greyscaled","Z8bIRPw")
AddImgurLink("csgo_daggers_marblefade","wTE6WAL")
AddImgurLink("csgo_daggers_night","wPHZj86")
AddImgurLink("csgo_daggers_rustcoat","tpO2WY6")
AddImgurLink("csgo_daggers_slaughter","iViFaOA")
AddImgurLink("csgo_daggers_tiger","6B0J1om")
AddImgurLink("csgo_daggers_ultraviolet","hLyzO8c")

AddImgurLink("csgo_cssource","ScC23Qo")
AddImgurLink("csgo_stiletto","4juELOm")
AddImgurLink("csgo_talon","ieCzSkm")
AddImgurLink("csgo_ursus","etUXkOe")
AddImgurLink("csgo_navaja","JJXuoTs")
AddImgurLink("csgo_tactical","I70jCLo")
AddImgurLink("csgo_default_knife","lyLS4fu")
AddImgurLink("csgo_default_golden","6Tgx1M1")
AddImgurLink("csgo_default_t","iMXoSbe")
AddImgurLink("csgo_default_t_golden","keGICQp")

AddImgurLink("csgo_falchion","Awc8Xju")
AddImgurLink("csgo_falchion_bluesteel","oiGI5Il")
AddImgurLink("csgo_falchion_boreal","T4EvVeP")
AddImgurLink("csgo_falchion_bright_water","Y5keRlz")
AddImgurLink("csgo_falchion_case","c813PJW")
AddImgurLink("csgo_falchion_crimsonwebs","VV00lAY")
AddImgurLink("csgo_falchion_damascus","pLxJFVq")
AddImgurLink("csgo_falchion_fade","TSpZtme")
AddImgurLink("csgo_falchion_ddpat","CNddiVk")
AddImgurLink("csgo_falchion_freehand","RrkcS7z")
AddImgurLink("csgo_falchion_gamma_doppler","tB7MyAv")
AddImgurLink("csgo_falchion_marblefade","rfeL02x")
AddImgurLink("csgo_falchion_night","s7y4wCB")
AddImgurLink("csgo_falchion_rustcoat","dYjX0Lb")
AddImgurLink("csgo_falchion_slaughter","kYy3ziH")
AddImgurLink("csgo_falchion_tiger","YngVR3h")
AddImgurLink("csgo_falchion_ultraviolet","VB0SRDd")

AddImgurLink("csgo_flip","C3cvHpG")
AddImgurLink("csgo_flip_autotronic","ez5SI4L")
AddImgurLink("csgo_flip_black_laminate","5J1lwir")
AddImgurLink("csgo_flip_bluesteel","z14ijCl")
AddImgurLink("csgo_flip_boreal","u5fbpjf")
AddImgurLink("csgo_flip_bright_water","UKViWi0")
AddImgurLink("csgo_flip_case","XcXfuwG")
AddImgurLink("csgo_flip_crimsonwebs","RSgvWkV")
AddImgurLink("csgo_flip_damascus","G6HsQlf")
AddImgurLink("csgo_flip_fade","lGZ8lWw")
AddImgurLink("csgo_flip_ddpat","akJb0wO")
AddImgurLink("csgo_flip_freehand","ie3FP9T")
AddImgurLink("csgo_flip_gamma_doppler","61VH3IW")
AddImgurLink("csgo_flip_lore","DyepeVJ")
AddImgurLink("csgo_flip_marblefade","0Ov0mr2")
AddImgurLink("csgo_flip_night","zyCf4K7")
AddImgurLink("csgo_flip_rustcoat","nF2QH1y")
AddImgurLink("csgo_flip_slaughter","S15awsm")
AddImgurLink("csgo_flip_tiger","NnFhcta")
AddImgurLink("csgo_flip_ultraviolet","vo9upLV")

AddImgurLink("csgo_gut","ePaS2ET")
AddImgurLink("csgo_gut_autotronic","zxBRjrh")
AddImgurLink("csgo_gut_black_laminate","wRMMJL6")
AddImgurLink("csgo_gut_bluesteel","UBiiND4")
AddImgurLink("csgo_gut_boreal","mXtiQCr")
AddImgurLink("csgo_gut_bright_water","u4i6skh")
AddImgurLink("csgo_gut_case","goC3SYe")
AddImgurLink("csgo_gut_crimsonwebs","vE8bOBS")
AddImgurLink("csgo_gut_damascus","yolx5vq")
AddImgurLink("csgo_gut_fade","PK3ztW1")
AddImgurLink("csgo_gut_ddpat","cjAuGqR")
AddImgurLink("csgo_gut_freehand","7HiMTM1")
AddImgurLink("csgo_gut_gamma_doppler","4zJm5JL")
AddImgurLink("csgo_gut_lore","ZY1ZYMp")
AddImgurLink("csgo_gut_marblefade","4ksZZPJ")
AddImgurLink("csgo_gut_night","vivlGlT")
AddImgurLink("csgo_gut_rustcoat","n25JduJ")
AddImgurLink("csgo_gut_slaughter","oFoBmqp")
AddImgurLink("csgo_gut_tiger","KArOQ46")
AddImgurLink("csgo_gut_ultraviolet","PQyfTwF")

AddImgurLink("csgo_huntsman","a1Tu065")
AddImgurLink("csgo_huntsman_bluesteel","3husRmT")
AddImgurLink("csgo_huntsman_boreal","3cwOXln")
AddImgurLink("csgo_huntsman_bright_water","jpJC2OB")
AddImgurLink("csgo_huntsman_case","p4hU6cv")
AddImgurLink("csgo_huntsman_crimsonwebs","5tXC47D")
AddImgurLink("csgo_huntsman_damascus","aRCn5LC")
AddImgurLink("csgo_huntsman_fade","zV0Fjr2")
AddImgurLink("csgo_huntsman_ddpat","gAZEKD9")
AddImgurLink("csgo_huntsman_freehand","hbRXXAo")
AddImgurLink("csgo_huntsman_gamma_doppler","uFmXbEt")
AddImgurLink("csgo_huntsman_marblefade","urcklP6")
AddImgurLink("csgo_huntsman_night","nOCdppl")
AddImgurLink("csgo_huntsman_rustcoat","50GFn5G")
AddImgurLink("csgo_huntsman_slaughter","O3xuHod")
AddImgurLink("csgo_huntsman_tiger","ksXX3cw")
AddImgurLink("csgo_huntsman_ultraviolet","p6y495A")

AddImgurLink("csgo_karambit","1uMf2hR")
AddImgurLink("csgo_karambit_autotronic","0ZXEvow")
AddImgurLink("csgo_karambit_black_laminate","67Ww1Dd")
AddImgurLink("csgo_karambit_bluesteel","9KMcbF3")
AddImgurLink("csgo_karambit_boreal","CQj8i0e")
AddImgurLink("csgo_karambit_bright_water","I3z2wUG")
AddImgurLink("csgo_karambit_case","pBfFlUq")
AddImgurLink("csgo_karambit_crimsonwebs","t6gZRpc")
AddImgurLink("csgo_karambit_damascus","NhcaTDP")
AddImgurLink("csgo_karambit_fade","VAg4nov")
AddImgurLink("csgo_karambit_ddpat","qQtAfwZ")
AddImgurLink("csgo_karambit_freehand","V4yFTK9")
AddImgurLink("csgo_karambit_gamma_doppler","QjTbzCH")
AddImgurLink("csgo_karambit_lore","SyUwVZB")
AddImgurLink("csgo_karambit_marblefade","TnYwJmE")
AddImgurLink("csgo_karambit_night","rDBWT94")
AddImgurLink("csgo_karambit_rustcoat","GXossKA")
AddImgurLink("csgo_karambit_slaughter","yhxz274")
AddImgurLink("csgo_karambit_tiger","K1hd8tp")
AddImgurLink("csgo_karambit_ultraviolet","z6hN61V")

AddImgurLink("csgo_m9","2glRcX0")
AddImgurLink("csgo_m9_autotronic","TGYKB2Z")
AddImgurLink("csgo_m9_black_laminate","TVfq6Sz")
AddImgurLink("csgo_m9_bluesteel","NbdWTjx")
AddImgurLink("csgo_m9_boreal","rfCBM24")
AddImgurLink("csgo_m9_bright_water","i1CEpIL")
AddImgurLink("csgo_m9_case","7k8TkpG")
AddImgurLink("csgo_m9_crimsonwebs","dSAXuJw")
AddImgurLink("csgo_m9_damascus","esGVUYE")
AddImgurLink("csgo_m9_fade","0lsjf1O")
AddImgurLink("csgo_m9_ddpat","gJ7sdKX")
AddImgurLink("csgo_m9_freehand","2fLJ9qs")
AddImgurLink("csgo_m9_gamma_doppler","kCwfCDy")
AddImgurLink("csgo_m9_lore","LhebpLs")
AddImgurLink("csgo_m9_marblefade","iUdVLqJ")
AddImgurLink("csgo_m9_night","pAoHjFW")
AddImgurLink("csgo_m9_rustcoat","fEsaikD")
AddImgurLink("csgo_m9_slaughter","OTcDZ2c")
AddImgurLink("csgo_m9_tiger","6qIbrHb")
AddImgurLink("csgo_m9_ultraviolet","tou3Hzb")


// Adds all the Xenin Deathscreens to the auto imgur search
if XeninDS then
    for k,v in pairs(XeninDS.Config.cards) do
        if v and v.src then
            AddImgurLink(k,v.src)
        end
    end
end
