-- ============================================================
-- BRICKS UNBOXING BASE CONFIG
-- 6 Weapon-Type Cases: Pistol, SMG, Rifle, Shotgun, Sniper, Heavy
-- 78 weapons × 7 rarities = 546 items
-- Auto-generated - do not edit manually
-- ============================================================

BRICKS_SERVER = BRICKS_SERVER or {}
BRICKS_SERVER.BASECONFIG = BRICKS_SERVER.BASECONFIG or {}

-- ============================================================
-- MODULE ENABLEMENT (required for bricks framework to load unboxing)
-- ============================================================
BRICKS_SERVER.BASECONFIG.MODULES = BRICKS_SERVER.BASECONFIG.MODULES or {}
BRICKS_SERVER.BASECONFIG.MODULES["unboxing"] = { true, {
    ["marketplace"] = true,
    ["rewards"] = true,
    ["trading"] = true,
} }

-- ============================================================
-- UNBOXING CONFIG
-- ============================================================
BRICKS_SERVER.BASECONFIG.UNBOXING = BRICKS_SERVER.BASECONFIG.UNBOXING or {}

-- Core settings
BRICKS_SERVER.BASECONFIG.UNBOXING["Case UI Open Time"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Case UI Open Time"] or 5
BRICKS_SERVER.BASECONFIG.UNBOXING["Case Open Time"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Case Open Time"] or 5
BRICKS_SERVER.BASECONFIG.UNBOXING["Activity Entry Limit"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Activity Entry Limit"] or 25
BRICKS_SERVER.BASECONFIG.UNBOXING["Auction Minimum Starting Price"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Auction Minimum Starting Price"] or 1000
BRICKS_SERVER.BASECONFIG.UNBOXING["Auction Maximum Starting Price"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Auction Maximum Starting Price"] or 1000000000
BRICKS_SERVER.BASECONFIG.UNBOXING["Auction Minimum Duration"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Auction Minimum Duration"] or 600
BRICKS_SERVER.BASECONFIG.UNBOXING["Auction Maximum Duration"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Auction Maximum Duration"] or 604800
BRICKS_SERVER.BASECONFIG.UNBOXING["Auctions Per Page"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Auctions Per Page"] or 12
BRICKS_SERVER.BASECONFIG.UNBOXING["Auctions Minimum Bid Increase"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Auctions Minimum Bid Increase"] or 1.1
BRICKS_SERVER.BASECONFIG.UNBOXING["Dead Auction Remove Time"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Dead Auction Remove Time"] or 259200
BRICKS_SERVER.BASECONFIG.UNBOXING["Cases Leaderboard Limit"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Cases Leaderboard Limit"] or 10
BRICKS_SERVER.BASECONFIG.UNBOXING["Disable Item Halos"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Disable Item Halos"] or false
BRICKS_SERVER.BASECONFIG.UNBOXING["Disable Case Collisions"] = BRICKS_SERVER.BASECONFIG.UNBOXING["Disable Case Collisions"] or false

-- ============================================================
-- 546 ITEMS (78 weapons × 7 rarities)
-- ============================================================
BRICKS_SERVER.BASECONFIG.UNBOXING.Items = {
    [1] = { Name = "Colt 1911", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_colt1911" } },
    [2] = { Name = "S&W Model 3 Russian", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_model3russian" } },
    [3] = { Name = "Glock 18", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_glock" } },
    [4] = { Name = "HK45C", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_hk45" } },
    [5] = { Name = "Luger P08", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_luger" } },
    [7] = { Name = "SIG P229R", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_sig_p229r" } },
    [8] = { Name = "HK USP", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_usp" } },
    [9] = { Name = "Remington 1858", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_remington1858" } },
    [10] = { Name = "Desert Eagle", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_deagle" } },
    [11] = { Name = "Colt Python", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_coltpython" } },
    [12] = { Name = "S&W Model 627", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_model627" } },
    [13] = { Name = "S&W Model 29 Satan", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m29satan" } },
    [14] = { Name = "S&W Model 500", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_model500" } },
    [15] = { Name = "Taurus Raging Bull", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_ragingbull" } },
    [16] = { Name = "TEC-9", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_tec9" } },
    [17] = { Name = "Colt 1911", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_colt1911" } },
    [18] = { Name = "S&W Model 3 Russian", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_model3russian" } },
    [19] = { Name = "Glock 18", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_glock" } },
    [20] = { Name = "HK45C", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_hk45" } },
    [21] = { Name = "Luger P08", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_luger" } },
    [23] = { Name = "SIG P229R", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_sig_p229r" } },
    [24] = { Name = "HK USP", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_usp" } },
    [25] = { Name = "Remington 1858", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_remington1858" } },
    [26] = { Name = "Desert Eagle", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_deagle" } },
    [27] = { Name = "Colt Python", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_coltpython" } },
    [28] = { Name = "S&W Model 627", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_model627" } },
    [29] = { Name = "S&W Model 29 Satan", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m29satan" } },
    [30] = { Name = "S&W Model 500", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_model500" } },
    [31] = { Name = "Taurus Raging Bull", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_ragingbull" } },
    [32] = { Name = "TEC-9", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_tec9" } },
    [33] = { Name = "Colt 1911", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_colt1911" } },
    [34] = { Name = "S&W Model 3 Russian", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_model3russian" } },
    [35] = { Name = "Glock 18", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_glock" } },
    [36] = { Name = "HK45C", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_hk45" } },
    [37] = { Name = "Luger P08", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_luger" } },
    [39] = { Name = "SIG P229R", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_sig_p229r" } },
    [40] = { Name = "HK USP", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_usp" } },
    [41] = { Name = "Remington 1858", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_remington1858" } },
    [42] = { Name = "Desert Eagle", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_deagle" } },
    [43] = { Name = "Colt Python", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_coltpython" } },
    [44] = { Name = "S&W Model 627", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_model627" } },
    [45] = { Name = "S&W Model 29 Satan", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m29satan" } },
    [46] = { Name = "S&W Model 500", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_model500" } },
    [47] = { Name = "Taurus Raging Bull", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_ragingbull" } },
    [48] = { Name = "TEC-9", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_tec9" } },
    [49] = { Name = "Colt 1911", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_colt1911" } },
    [50] = { Name = "S&W Model 3 Russian", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_model3russian" } },
    [51] = { Name = "Glock 18", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_glock" } },
    [52] = { Name = "HK45C", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_hk45" } },
    [53] = { Name = "Luger P08", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_luger" } },
    [55] = { Name = "SIG P229R", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_sig_p229r" } },
    [56] = { Name = "HK USP", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_usp" } },
    [57] = { Name = "Remington 1858", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_remington1858" } },
    [58] = { Name = "Desert Eagle", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_deagle" } },
    [59] = { Name = "Colt Python", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_coltpython" } },
    [60] = { Name = "S&W Model 627", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_model627" } },
    [61] = { Name = "S&W Model 29 Satan", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m29satan" } },
    [62] = { Name = "S&W Model 500", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_model500" } },
    [63] = { Name = "Taurus Raging Bull", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_ragingbull" } },
    [64] = { Name = "TEC-9", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_tec9" } },
    [65] = { Name = "Colt 1911", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_colt1911" } },
    [66] = { Name = "S&W Model 3 Russian", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_model3russian" } },
    [67] = { Name = "Glock 18", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_glock" } },
    [68] = { Name = "HK45C", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_hk45" } },
    [69] = { Name = "Luger P08", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_luger" } },
    [71] = { Name = "SIG P229R", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_sig_p229r" } },
    [72] = { Name = "HK USP", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_usp" } },
    [73] = { Name = "Remington 1858", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_remington1858" } },
    [74] = { Name = "Desert Eagle", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_deagle" } },
    [75] = { Name = "Colt Python", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_coltpython" } },
    [76] = { Name = "S&W Model 627", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_model627" } },
    [77] = { Name = "S&W Model 29 Satan", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m29satan" } },
    [78] = { Name = "S&W Model 500", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_model500" } },
    [79] = { Name = "Taurus Raging Bull", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_ragingbull" } },
    [80] = { Name = "TEC-9", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_tec9" } },
    [81] = { Name = "Colt 1911", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_colt1911" } },
    [82] = { Name = "S&W Model 3 Russian", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_model3russian" } },
    [83] = { Name = "Glock 18", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_glock" } },
    [84] = { Name = "HK45C", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_hk45" } },
    [85] = { Name = "Luger P08", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_luger" } },
    [87] = { Name = "SIG P229R", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_sig_p229r" } },
    [88] = { Name = "HK USP", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_usp" } },
    [89] = { Name = "Remington 1858", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_remington1858" } },
    [90] = { Name = "Desert Eagle", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_deagle" } },
    [91] = { Name = "Colt Python", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_coltpython" } },
    [92] = { Name = "S&W Model 627", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_model627" } },
    [93] = { Name = "S&W Model 29 Satan", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m29satan" } },
    [94] = { Name = "S&W Model 500", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_model500" } },
    [95] = { Name = "Taurus Raging Bull", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_ragingbull" } },
    [96] = { Name = "TEC-9", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_tec9" } },
    [97] = { Name = "Colt 1911", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_colt1911" } },
    [98] = { Name = "S&W Model 3 Russian", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_model3russian" } },
    [99] = { Name = "Glock 18", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_glock" } },
    [100] = { Name = "HK45C", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_hk45" } },
    [101] = { Name = "Luger P08", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_luger" } },
    [103] = { Name = "SIG P229R", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_sig_p229r" } },
    [104] = { Name = "HK USP", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_usp" } },
    [105] = { Name = "Remington 1858", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_remington1858" } },
    [106] = { Name = "Desert Eagle", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_deagle" } },
    [107] = { Name = "Colt Python", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_coltpython" } },
    [108] = { Name = "S&W Model 627", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_model627" } },
    [109] = { Name = "S&W Model 29 Satan", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m29satan" } },
    [110] = { Name = "S&W Model 500", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_model500" } },
    [111] = { Name = "Taurus Raging Bull", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_ragingbull" } },
    [112] = { Name = "TEC-9", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_tec9" } },
    [114] = { Name = "MP5", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_mp5" } },
    [115] = { Name = "MP5SD", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_mp5sd" } },
    [116] = { Name = "MP7", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_mp7" } },
    [117] = { Name = "MP9", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_mp9" } },
    [118] = { Name = "Sten", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_sten" } },
    [119] = { Name = "UMP-45", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_ump45" } },
    [120] = { Name = "Bizon PP-19", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_bizonp19" } },
    [121] = { Name = "Thompson M1A1", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_thompson" } },
    [122] = { Name = "Magpul PDR", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_magpulpdr" } },
    [123] = { Name = "FN P90", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_smgp90" } },
    [124] = { Name = "Uzi", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_uzi" } },
    [125] = { Name = "Kriss Vector", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_vector" } },
    [126] = { Name = "Honey Badger", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_honeybadger" } },
    [128] = { Name = "MP5", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_mp5" } },
    [129] = { Name = "MP5SD", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_mp5sd" } },
    [130] = { Name = "MP7", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_mp7" } },
    [131] = { Name = "MP9", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_mp9" } },
    [132] = { Name = "Sten", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_sten" } },
    [133] = { Name = "UMP-45", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_ump45" } },
    [134] = { Name = "Bizon PP-19", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_bizonp19" } },
    [135] = { Name = "Thompson M1A1", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_thompson" } },
    [136] = { Name = "Magpul PDR", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_magpulpdr" } },
    [137] = { Name = "FN P90", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_smgp90" } },
    [138] = { Name = "Uzi", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_uzi" } },
    [139] = { Name = "Kriss Vector", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_vector" } },
    [140] = { Name = "Honey Badger", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_honeybadger" } },
    [142] = { Name = "MP5", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_mp5" } },
    [143] = { Name = "MP5SD", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_mp5sd" } },
    [144] = { Name = "MP7", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_mp7" } },
    [145] = { Name = "MP9", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_mp9" } },
    [146] = { Name = "Sten", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_sten" } },
    [147] = { Name = "UMP-45", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_ump45" } },
    [148] = { Name = "Bizon PP-19", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_bizonp19" } },
    [149] = { Name = "Thompson M1A1", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_thompson" } },
    [150] = { Name = "Magpul PDR", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_magpulpdr" } },
    [151] = { Name = "FN P90", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_smgp90" } },
    [152] = { Name = "Uzi", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_uzi" } },
    [153] = { Name = "Kriss Vector", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_vector" } },
    [154] = { Name = "Honey Badger", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_honeybadger" } },
    [156] = { Name = "MP5", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_mp5" } },
    [157] = { Name = "MP5SD", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_mp5sd" } },
    [158] = { Name = "MP7", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_mp7" } },
    [159] = { Name = "MP9", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_mp9" } },
    [160] = { Name = "Sten", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_sten" } },
    [161] = { Name = "UMP-45", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_ump45" } },
    [162] = { Name = "Bizon PP-19", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_bizonp19" } },
    [163] = { Name = "Thompson M1A1", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_thompson" } },
    [164] = { Name = "Magpul PDR", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_magpulpdr" } },
    [165] = { Name = "FN P90", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_smgp90" } },
    [166] = { Name = "Uzi", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_uzi" } },
    [167] = { Name = "Kriss Vector", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_vector" } },
    [168] = { Name = "Honey Badger", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_honeybadger" } },
    [170] = { Name = "MP5", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_mp5" } },
    [171] = { Name = "MP5SD", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_mp5sd" } },
    [172] = { Name = "MP7", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_mp7" } },
    [173] = { Name = "MP9", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_mp9" } },
    [174] = { Name = "Sten", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_sten" } },
    [175] = { Name = "UMP-45", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_ump45" } },
    [176] = { Name = "Bizon PP-19", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_bizonp19" } },
    [177] = { Name = "Thompson M1A1", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_thompson" } },
    [178] = { Name = "Magpul PDR", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_magpulpdr" } },
    [179] = { Name = "FN P90", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_smgp90" } },
    [180] = { Name = "Uzi", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_uzi" } },
    [181] = { Name = "Kriss Vector", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_vector" } },
    [182] = { Name = "Honey Badger", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_honeybadger" } },
    [184] = { Name = "MP5", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_mp5" } },
    [185] = { Name = "MP5SD", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_mp5sd" } },
    [186] = { Name = "MP7", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_mp7" } },
    [187] = { Name = "MP9", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_mp9" } },
    [188] = { Name = "Sten", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_sten" } },
    [189] = { Name = "UMP-45", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_ump45" } },
    [190] = { Name = "Bizon PP-19", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_bizonp19" } },
    [191] = { Name = "Thompson M1A1", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_thompson" } },
    [192] = { Name = "Magpul PDR", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_magpulpdr" } },
    [193] = { Name = "FN P90", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_smgp90" } },
    [194] = { Name = "Uzi", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_uzi" } },
    [195] = { Name = "Kriss Vector", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_vector" } },
    [196] = { Name = "Honey Badger", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_honeybadger" } },
    [198] = { Name = "MP5", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_mp5" } },
    [199] = { Name = "MP5SD", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_mp5sd" } },
    [200] = { Name = "MP7", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_mp7" } },
    [201] = { Name = "MP9", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_mp9" } },
    [202] = { Name = "Sten", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_sten" } },
    [203] = { Name = "UMP-45", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_ump45" } },
    [204] = { Name = "Bizon PP-19", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_bizonp19" } },
    [205] = { Name = "Thompson M1A1", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_thompson" } },
    [206] = { Name = "Magpul PDR", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_magpulpdr" } },
    [207] = { Name = "FN P90", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_smgp90" } },
    [208] = { Name = "Uzi", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_uzi" } },
    [209] = { Name = "Kriss Vector", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_vector" } },
    [210] = { Name = "Honey Badger", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_honeybadger" } },
    [211] = { Name = "AK-47", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_ak47" } },
    [212] = { Name = "AK-74", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_ak74" } },
    [213] = { Name = "M4A1", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m4a1" } },
    [214] = { Name = "Remington ACR", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_acr" } },
    [215] = { Name = "HK416", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m416" } },
    [216] = { Name = "FN FAL", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_fal" } },
    [217] = { Name = "G3A3", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_g3a3" } },
    [218] = { Name = "G36", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_g36" } },
    [219] = { Name = "L85A2", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_l85" } },
    [220] = { Name = "AMD-65", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_amd65" } },
    [221] = { Name = "AN-94", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_an94" } },
    [222] = { Name = "SCAR-H", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_scar" } },
    [223] = { Name = "AS VAL", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_val" } },
    [225] = { Name = "TAR-21", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_tar21" } },
    [226] = { Name = "SR-3M Vikhr", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_vikhr" } },
    [227] = { Name = "M14 SP", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m14sp" } },
    [228] = { Name = "M16A4 ACOG", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m16a4_acog" } },
    [229] = { Name = "Winchester 1873", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_winchester73" } },
    [230] = { Name = "AK-47", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_ak47" } },
    [231] = { Name = "AK-74", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_ak74" } },
    [232] = { Name = "M4A1", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m4a1" } },
    [233] = { Name = "Remington ACR", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_acr" } },
    [234] = { Name = "HK416", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m416" } },
    [235] = { Name = "FN FAL", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_fal" } },
    [236] = { Name = "G3A3", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_g3a3" } },
    [237] = { Name = "G36", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_g36" } },
    [238] = { Name = "L85A2", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_l85" } },
    [239] = { Name = "AMD-65", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_amd65" } },
    [240] = { Name = "AN-94", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_an94" } },
    [241] = { Name = "SCAR-H", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_scar" } },
    [242] = { Name = "AS VAL", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_val" } },
    [244] = { Name = "TAR-21", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_tar21" } },
    [245] = { Name = "SR-3M Vikhr", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_vikhr" } },
    [246] = { Name = "M14 SP", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m14sp" } },
    [247] = { Name = "M16A4 ACOG", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m16a4_acog" } },
    [248] = { Name = "Winchester 1873", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_winchester73" } },
    [249] = { Name = "AK-47", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_ak47" } },
    [250] = { Name = "AK-74", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_ak74" } },
    [251] = { Name = "M4A1", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m4a1" } },
    [252] = { Name = "Remington ACR", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_acr" } },
    [253] = { Name = "HK416", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m416" } },
    [254] = { Name = "FN FAL", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_fal" } },
    [255] = { Name = "G3A3", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_g3a3" } },
    [256] = { Name = "G36", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_g36" } },
    [257] = { Name = "L85A2", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_l85" } },
    [258] = { Name = "AMD-65", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_amd65" } },
    [259] = { Name = "AN-94", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_an94" } },
    [260] = { Name = "SCAR-H", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_scar" } },
    [261] = { Name = "AS VAL", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_val" } },
    [263] = { Name = "TAR-21", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_tar21" } },
    [264] = { Name = "SR-3M Vikhr", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_vikhr" } },
    [265] = { Name = "M14 SP", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m14sp" } },
    [266] = { Name = "M16A4 ACOG", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m16a4_acog" } },
    [267] = { Name = "Winchester 1873", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_winchester73" } },
    [268] = { Name = "AK-47", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_ak47" } },
    [269] = { Name = "AK-74", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_ak74" } },
    [270] = { Name = "M4A1", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m4a1" } },
    [271] = { Name = "Remington ACR", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_acr" } },
    [272] = { Name = "HK416", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m416" } },
    [273] = { Name = "FN FAL", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_fal" } },
    [274] = { Name = "G3A3", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_g3a3" } },
    [275] = { Name = "G36", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_g36" } },
    [276] = { Name = "L85A2", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_l85" } },
    [277] = { Name = "AMD-65", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_amd65" } },
    [278] = { Name = "AN-94", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_an94" } },
    [279] = { Name = "SCAR-H", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_scar" } },
    [280] = { Name = "AS VAL", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_val" } },
    [282] = { Name = "TAR-21", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_tar21" } },
    [283] = { Name = "SR-3M Vikhr", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_vikhr" } },
    [284] = { Name = "M14 SP", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m14sp" } },
    [285] = { Name = "M16A4 ACOG", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m16a4_acog" } },
    [286] = { Name = "Winchester 1873", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_winchester73" } },
    [287] = { Name = "AK-47", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_ak47" } },
    [288] = { Name = "AK-74", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_ak74" } },
    [289] = { Name = "M4A1", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m4a1" } },
    [290] = { Name = "Remington ACR", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_acr" } },
    [291] = { Name = "HK416", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m416" } },
    [292] = { Name = "FN FAL", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_fal" } },
    [293] = { Name = "G3A3", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_g3a3" } },
    [294] = { Name = "G36", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_g36" } },
    [295] = { Name = "L85A2", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_l85" } },
    [296] = { Name = "AMD-65", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_amd65" } },
    [297] = { Name = "AN-94", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_an94" } },
    [298] = { Name = "SCAR-H", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_scar" } },
    [299] = { Name = "AS VAL", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_val" } },
    [301] = { Name = "TAR-21", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_tar21" } },
    [302] = { Name = "SR-3M Vikhr", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_vikhr" } },
    [303] = { Name = "M14 SP", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m14sp" } },
    [304] = { Name = "M16A4 ACOG", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m16a4_acog" } },
    [305] = { Name = "Winchester 1873", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_winchester73" } },
    [306] = { Name = "AK-47", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_ak47" } },
    [307] = { Name = "AK-74", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_ak74" } },
    [308] = { Name = "M4A1", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m4a1" } },
    [309] = { Name = "Remington ACR", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_acr" } },
    [310] = { Name = "HK416", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m416" } },
    [311] = { Name = "FN FAL", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_fal" } },
    [312] = { Name = "G3A3", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_g3a3" } },
    [313] = { Name = "G36", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_g36" } },
    [314] = { Name = "L85A2", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_l85" } },
    [315] = { Name = "AMD-65", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_amd65" } },
    [316] = { Name = "AN-94", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_an94" } },
    [317] = { Name = "SCAR-H", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_scar" } },
    [318] = { Name = "AS VAL", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_val" } },
    [320] = { Name = "TAR-21", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_tar21" } },
    [321] = { Name = "SR-3M Vikhr", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_vikhr" } },
    [322] = { Name = "M14 SP", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m14sp" } },
    [323] = { Name = "M16A4 ACOG", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m16a4_acog" } },
    [324] = { Name = "Winchester 1873", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_winchester73" } },
    [325] = { Name = "AK-47", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_ak47" } },
    [326] = { Name = "AK-74", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_ak74" } },
    [327] = { Name = "M4A1", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m4a1" } },
    [328] = { Name = "Remington ACR", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_acr" } },
    [329] = { Name = "HK416", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m416" } },
    [330] = { Name = "FN FAL", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_fal" } },
    [331] = { Name = "G3A3", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_g3a3" } },
    [332] = { Name = "G36", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_g36" } },
    [333] = { Name = "L85A2", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_l85" } },
    [334] = { Name = "AMD-65", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_amd65" } },
    [335] = { Name = "AN-94", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_an94" } },
    [336] = { Name = "SCAR-H", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_scar" } },
    [337] = { Name = "AS VAL", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_val" } },
    [339] = { Name = "TAR-21", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_tar21" } },
    [340] = { Name = "SR-3M Vikhr", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_vikhr" } },
    [341] = { Name = "M14 SP", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m14sp" } },
    [342] = { Name = "M16A4 ACOG", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m16a4_acog" } },
    [343] = { Name = "Winchester 1873", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_winchester73" } },
    [344] = { Name = "Browning Auto-5", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_browningauto5" } },
    [345] = { Name = "Ithaca M37", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_ithacam37" } },
    [346] = { Name = "Mossberg 590", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_mossberg590" } },
    [347] = { Name = "Remington 870", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_remington870" } },
    [348] = { Name = "SPAS-12", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_spas12" } },
    [349] = { Name = "Benelli M3", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m3" } },
    [351] = { Name = "Pancor Jackhammer", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_jackhammer" } },
    [352] = { Name = "Striker-12", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_striker12" } },
    [353] = { Name = "USAS-12", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_usas" } },
    [354] = { Name = "Double Barrel", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_dbarrel" } },
    [355] = { Name = "Browning Auto-5", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_browningauto5" } },
    [356] = { Name = "Ithaca M37", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_ithacam37" } },
    [357] = { Name = "Mossberg 590", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_mossberg590" } },
    [358] = { Name = "Remington 870", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_remington870" } },
    [359] = { Name = "SPAS-12", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_spas12" } },
    [360] = { Name = "Benelli M3", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m3" } },
    [362] = { Name = "Pancor Jackhammer", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_jackhammer" } },
    [363] = { Name = "Striker-12", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_striker12" } },
    [364] = { Name = "USAS-12", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_usas" } },
    [365] = { Name = "Double Barrel", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_dbarrel" } },
    [366] = { Name = "Browning Auto-5", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_browningauto5" } },
    [367] = { Name = "Ithaca M37", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_ithacam37" } },
    [368] = { Name = "Mossberg 590", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_mossberg590" } },
    [369] = { Name = "Remington 870", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_remington870" } },
    [370] = { Name = "SPAS-12", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_spas12" } },
    [371] = { Name = "Benelli M3", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m3" } },
    [373] = { Name = "Pancor Jackhammer", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_jackhammer" } },
    [374] = { Name = "Striker-12", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_striker12" } },
    [375] = { Name = "USAS-12", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_usas" } },
    [376] = { Name = "Double Barrel", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_dbarrel" } },
    [377] = { Name = "Browning Auto-5", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_browningauto5" } },
    [378] = { Name = "Ithaca M37", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_ithacam37" } },
    [379] = { Name = "Mossberg 590", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_mossberg590" } },
    [380] = { Name = "Remington 870", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_remington870" } },
    [381] = { Name = "SPAS-12", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_spas12" } },
    [382] = { Name = "Benelli M3", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m3" } },
    [384] = { Name = "Pancor Jackhammer", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_jackhammer" } },
    [385] = { Name = "Striker-12", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_striker12" } },
    [386] = { Name = "USAS-12", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_usas" } },
    [387] = { Name = "Double Barrel", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_dbarrel" } },
    [388] = { Name = "Browning Auto-5", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_browningauto5" } },
    [389] = { Name = "Ithaca M37", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_ithacam37" } },
    [390] = { Name = "Mossberg 590", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_mossberg590" } },
    [391] = { Name = "Remington 870", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_remington870" } },
    [392] = { Name = "SPAS-12", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_spas12" } },
    [393] = { Name = "Benelli M3", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m3" } },
    [395] = { Name = "Pancor Jackhammer", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_jackhammer" } },
    [396] = { Name = "Striker-12", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_striker12" } },
    [397] = { Name = "USAS-12", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_usas" } },
    [398] = { Name = "Double Barrel", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_dbarrel" } },
    [399] = { Name = "Browning Auto-5", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_browningauto5" } },
    [400] = { Name = "Ithaca M37", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_ithacam37" } },
    [401] = { Name = "Mossberg 590", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_mossberg590" } },
    [402] = { Name = "Remington 870", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_remington870" } },
    [403] = { Name = "SPAS-12", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_spas12" } },
    [404] = { Name = "Benelli M3", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m3" } },
    [406] = { Name = "Pancor Jackhammer", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_jackhammer" } },
    [407] = { Name = "Striker-12", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_striker12" } },
    [408] = { Name = "USAS-12", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_usas" } },
    [409] = { Name = "Double Barrel", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_dbarrel" } },
    [410] = { Name = "Browning Auto-5", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_browningauto5" } },
    [411] = { Name = "Ithaca M37", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_ithacam37" } },
    [412] = { Name = "Mossberg 590", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_mossberg590" } },
    [413] = { Name = "Remington 870", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_remington870" } },
    [414] = { Name = "SPAS-12", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_spas12" } },
    [415] = { Name = "Benelli M3", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m3" } },
    [417] = { Name = "Pancor Jackhammer", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_jackhammer" } },
    [418] = { Name = "Striker-12", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_striker12" } },
    [419] = { Name = "USAS-12", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_usas" } },
    [420] = { Name = "Double Barrel", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_dbarrel" } },
    [421] = { Name = "M24", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m24" } },
    [422] = { Name = "PSG-1", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_psg1" } },
    [423] = { Name = "SVD Dragunov", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_dragunov" } },
    [424] = { Name = "SVT-40", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_svt40" } },
    [425] = { Name = "Remington 7615P", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_remington7615p" } },
    [426] = { Name = "HK SL8", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_sl8" } },
    [427] = { Name = "Contender G2", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_contender" } },
    [428] = { Name = "Intervention", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_intervention" } },
    [429] = { Name = "M98B", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m98b" } },
    [430] = { Name = "AW50", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_aw50" } },
    [431] = { Name = "Barrett M82", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_barret_m82" } },
    [432] = { Name = "M24", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m24" } },
    [433] = { Name = "PSG-1", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_psg1" } },
    [434] = { Name = "SVD Dragunov", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_dragunov" } },
    [435] = { Name = "SVT-40", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_svt40" } },
    [436] = { Name = "Remington 7615P", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_remington7615p" } },
    [437] = { Name = "HK SL8", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_sl8" } },
    [438] = { Name = "Contender G2", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_contender" } },
    [439] = { Name = "Intervention", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_intervention" } },
    [440] = { Name = "M98B", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m98b" } },
    [441] = { Name = "AW50", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_aw50" } },
    [442] = { Name = "Barrett M82", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_barret_m82" } },
    [443] = { Name = "M24", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m24" } },
    [444] = { Name = "PSG-1", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_psg1" } },
    [445] = { Name = "SVD Dragunov", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_dragunov" } },
    [446] = { Name = "SVT-40", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_svt40" } },
    [447] = { Name = "Remington 7615P", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_remington7615p" } },
    [448] = { Name = "HK SL8", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_sl8" } },
    [449] = { Name = "Contender G2", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_contender" } },
    [450] = { Name = "Intervention", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_intervention" } },
    [451] = { Name = "M98B", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m98b" } },
    [452] = { Name = "AW50", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_aw50" } },
    [453] = { Name = "Barrett M82", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_barret_m82" } },
    [454] = { Name = "M24", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m24" } },
    [455] = { Name = "PSG-1", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_psg1" } },
    [456] = { Name = "SVD Dragunov", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_dragunov" } },
    [457] = { Name = "SVT-40", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_svt40" } },
    [458] = { Name = "Remington 7615P", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_remington7615p" } },
    [459] = { Name = "HK SL8", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_sl8" } },
    [460] = { Name = "Contender G2", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_contender" } },
    [461] = { Name = "Intervention", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_intervention" } },
    [462] = { Name = "M98B", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m98b" } },
    [463] = { Name = "AW50", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_aw50" } },
    [464] = { Name = "Barrett M82", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_barret_m82" } },
    [465] = { Name = "M24", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m24" } },
    [466] = { Name = "PSG-1", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_psg1" } },
    [467] = { Name = "SVD Dragunov", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_dragunov" } },
    [468] = { Name = "SVT-40", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_svt40" } },
    [469] = { Name = "Remington 7615P", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_remington7615p" } },
    [470] = { Name = "HK SL8", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_sl8" } },
    [471] = { Name = "Contender G2", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_contender" } },
    [472] = { Name = "Intervention", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_intervention" } },
    [473] = { Name = "M98B", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m98b" } },
    [474] = { Name = "AW50", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_aw50" } },
    [475] = { Name = "Barrett M82", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_barret_m82" } },
    [476] = { Name = "M24", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m24" } },
    [477] = { Name = "PSG-1", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_psg1" } },
    [478] = { Name = "SVD Dragunov", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_dragunov" } },
    [479] = { Name = "SVT-40", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_svt40" } },
    [480] = { Name = "Remington 7615P", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_remington7615p" } },
    [481] = { Name = "HK SL8", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_sl8" } },
    [482] = { Name = "Contender G2", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_contender" } },
    [483] = { Name = "Intervention", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_intervention" } },
    [484] = { Name = "M98B", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m98b" } },
    [485] = { Name = "AW50", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_aw50" } },
    [486] = { Name = "Barrett M82", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_barret_m82" } },
    [487] = { Name = "M24", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m24" } },
    [488] = { Name = "PSG-1", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_psg1" } },
    [489] = { Name = "SVD Dragunov", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_dragunov" } },
    [490] = { Name = "SVT-40", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_svt40" } },
    [491] = { Name = "Remington 7615P", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_remington7615p" } },
    [492] = { Name = "HK SL8", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_sl8" } },
    [493] = { Name = "Contender G2", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_contender" } },
    [494] = { Name = "Intervention", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_intervention" } },
    [495] = { Name = "M98B", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m98b" } },
    [496] = { Name = "AW50", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_aw50" } },
    [497] = { Name = "Barrett M82", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_barret_m82" } },
    [498] = { Name = "M249 SAW", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m249lmg" } },
    [499] = { Name = "M60", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m60" } },
    [500] = { Name = "PKM", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_pkm" } },
    [501] = { Name = "Ares Shrike", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_ares_shrike" } },
    [502] = { Name = "Minigun", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_minigun" } },
    [503] = { Name = "Milkor MGL", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_milkormgl" } },
    [504] = { Name = "M202 Flash", Type = "PermWeapon", Rarity = "Common", ReqInfo = { "m9k_m202" } },
    [505] = { Name = "M249 SAW", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m249lmg" } },
    [506] = { Name = "M60", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m60" } },
    [507] = { Name = "PKM", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_pkm" } },
    [508] = { Name = "Ares Shrike", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_ares_shrike" } },
    [509] = { Name = "Minigun", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_minigun" } },
    [510] = { Name = "Milkor MGL", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_milkormgl" } },
    [511] = { Name = "M202 Flash", Type = "PermWeapon", Rarity = "Uncommon", ReqInfo = { "m9k_m202" } },
    [512] = { Name = "M249 SAW", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m249lmg" } },
    [513] = { Name = "M60", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m60" } },
    [514] = { Name = "PKM", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_pkm" } },
    [515] = { Name = "Ares Shrike", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_ares_shrike" } },
    [516] = { Name = "Minigun", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_minigun" } },
    [517] = { Name = "Milkor MGL", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_milkormgl" } },
    [518] = { Name = "M202 Flash", Type = "PermWeapon", Rarity = "Rare", ReqInfo = { "m9k_m202" } },
    [519] = { Name = "M249 SAW", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m249lmg" } },
    [520] = { Name = "M60", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m60" } },
    [521] = { Name = "PKM", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_pkm" } },
    [522] = { Name = "Ares Shrike", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_ares_shrike" } },
    [523] = { Name = "Minigun", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_minigun" } },
    [524] = { Name = "Milkor MGL", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_milkormgl" } },
    [525] = { Name = "M202 Flash", Type = "PermWeapon", Rarity = "Epic", ReqInfo = { "m9k_m202" } },
    [526] = { Name = "M249 SAW", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m249lmg" } },
    [527] = { Name = "M60", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m60" } },
    [528] = { Name = "PKM", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_pkm" } },
    [529] = { Name = "Ares Shrike", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_ares_shrike" } },
    [530] = { Name = "Minigun", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_minigun" } },
    [531] = { Name = "Milkor MGL", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_milkormgl" } },
    [532] = { Name = "M202 Flash", Type = "PermWeapon", Rarity = "Legendary", ReqInfo = { "m9k_m202" } },
    [533] = { Name = "M249 SAW", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m249lmg" } },
    [534] = { Name = "M60", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m60" } },
    [535] = { Name = "PKM", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_pkm" } },
    [536] = { Name = "Ares Shrike", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_ares_shrike" } },
    [537] = { Name = "Minigun", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_minigun" } },
    [538] = { Name = "Milkor MGL", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_milkormgl" } },
    [539] = { Name = "M202 Flash", Type = "PermWeapon", Rarity = "Glitched", ReqInfo = { "m9k_m202" } },
    [540] = { Name = "M249 SAW", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m249lmg" } },
    [541] = { Name = "M60", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m60" } },
    [542] = { Name = "PKM", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_pkm" } },
    [543] = { Name = "Ares Shrike", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_ares_shrike" } },
    [544] = { Name = "Minigun", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_minigun" } },
    [545] = { Name = "Milkor MGL", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_milkormgl" } },
    [546] = { Name = "M202 Flash", Type = "PermWeapon", Rarity = "Mythical", ReqInfo = { "m9k_m202" } },
}

-- ============================================================
-- 6 WEAPON-TYPE CASES
-- ============================================================
BRICKS_SERVER.BASECONFIG.UNBOXING.Cases = {
    [1] = {
        Name = "Pistol Case", Model = 1, Rarity = "Common",
        Color = Color(200,200,200), Keys = { [1] = true },
        Items = {
            -- Common (w=40000)
            ["ITEM_1"] = { 4545 },
            ["ITEM_2"] = { 1562 },
            ["ITEM_3"] = { 781 },
            ["ITEM_4"] = { 446 },
            ["ITEM_5"] = { 250 },
            ["ITEM_7"] = { 4545 },
            ["ITEM_8"] = { 4545 },
            ["ITEM_9"] = { 4545 },
            ["ITEM_10"] = { 4545 },
            ["ITEM_11"] = { 4545 },
            ["ITEM_12"] = { 4545 },
            ["ITEM_13"] = { 4545 },
            ["ITEM_14"] = { 4545 },
            ["ITEM_15"] = { 4545 },
            ["ITEM_16"] = { 4545 },
            -- Uncommon (w=28000)
            ["ITEM_17"] = { 1562 },
            ["ITEM_18"] = { 1562 },
            ["ITEM_19"] = { 1562 },
            ["ITEM_20"] = { 1562 },
            ["ITEM_21"] = { 1562 },
            ["ITEM_23"] = { 1562 },
            ["ITEM_24"] = { 1562 },
            ["ITEM_25"] = { 1562 },
            ["ITEM_26"] = { 1562 },
            ["ITEM_27"] = { 1562 },
            ["ITEM_28"] = { 1562 },
            ["ITEM_29"] = { 1562 },
            ["ITEM_30"] = { 1562 },
            ["ITEM_31"] = { 1562 },
            ["ITEM_32"] = { 1562 },
            -- Rare (w=15000)
            ["ITEM_33"] = { 781 },
            ["ITEM_34"] = { 781 },
            ["ITEM_35"] = { 781 },
            ["ITEM_36"] = { 781 },
            ["ITEM_37"] = { 781 },
            ["ITEM_39"] = { 781 },
            ["ITEM_40"] = { 781 },
            ["ITEM_41"] = { 781 },
            ["ITEM_42"] = { 781 },
            ["ITEM_43"] = { 781 },
            ["ITEM_44"] = { 781 },
            ["ITEM_45"] = { 781 },
            ["ITEM_46"] = { 781 },
            ["ITEM_47"] = { 781 },
            ["ITEM_48"] = { 781 },
            -- Epic (w=13000)
            ["ITEM_49"] = { 446 },
            ["ITEM_50"] = { 446 },
            ["ITEM_51"] = { 446 },
            ["ITEM_52"] = { 446 },
            ["ITEM_53"] = { 446 },
            ["ITEM_55"] = { 446 },
            ["ITEM_56"] = { 446 },
            ["ITEM_57"] = { 446 },
            ["ITEM_58"] = { 446 },
            ["ITEM_59"] = { 446 },
            ["ITEM_60"] = { 446 },
            ["ITEM_61"] = { 446 },
            ["ITEM_62"] = { 446 },
            ["ITEM_63"] = { 446 },
            ["ITEM_64"] = { 446 },
            -- Legendary (w=2000)
            ["ITEM_65"] = { 250 },
            ["ITEM_66"] = { 250 },
            ["ITEM_67"] = { 250 },
            ["ITEM_68"] = { 250 },
            ["ITEM_69"] = { 250 },
            ["ITEM_71"] = { 250 },
            ["ITEM_72"] = { 250 },
            ["ITEM_73"] = { 250 },
            ["ITEM_74"] = { 250 },
            ["ITEM_75"] = { 250 },
            ["ITEM_76"] = { 250 },
            ["ITEM_77"] = { 250 },
            ["ITEM_78"] = { 250 },
            ["ITEM_79"] = { 250 },
            ["ITEM_80"] = { 250 },
            -- Glitched (w=1200)
            ["ITEM_81"] = { 48 },
            ["ITEM_82"] = { 48 },
            ["ITEM_83"] = { 48 },
            ["ITEM_84"] = { 48 },
            ["ITEM_85"] = { 48 },
            ["ITEM_87"] = { 48 },
            ["ITEM_88"] = { 48 },
            ["ITEM_89"] = { 48 },
            ["ITEM_90"] = { 48 },
            ["ITEM_91"] = { 48 },
            ["ITEM_92"] = { 48 },
            ["ITEM_93"] = { 48 },
            ["ITEM_94"] = { 48 },
            ["ITEM_95"] = { 48 },
            ["ITEM_96"] = { 48 },
            -- Mythical (w=700)
            ["ITEM_97"] = { 27 },
            ["ITEM_98"] = { 27 },
            ["ITEM_99"] = { 27 },
            ["ITEM_100"] = { 27 },
            ["ITEM_101"] = { 27 },
            ["ITEM_103"] = { 27 },
            ["ITEM_104"] = { 27 },
            ["ITEM_105"] = { 27 },
            ["ITEM_106"] = { 27 },
            ["ITEM_107"] = { 27 },
            ["ITEM_108"] = { 27 },
            ["ITEM_109"] = { 27 },
            ["ITEM_110"] = { 27 },
            ["ITEM_111"] = { 27 },
            ["ITEM_112"] = { 27 },
        }
    },
    [2] = {
        Name = "SMG Case", Model = 1, Rarity = "Common",
        Color = Color(104,255,104), Keys = { [2] = true },
        Items = {
            -- Common (w=40000)
            ["ITEM_114"] = { 3846 },
            ["ITEM_115"] = { 3846 },
            ["ITEM_116"] = { 3846 },
            ["ITEM_117"] = { 3846 },
            ["ITEM_118"] = { 3846 },
            ["ITEM_119"] = { 3846 },
            ["ITEM_120"] = { 3846 },
            ["ITEM_121"] = { 3846 },
            ["ITEM_122"] = { 3846 },
            ["ITEM_123"] = { 3846 },
            ["ITEM_124"] = { 3846 },
            ["ITEM_125"] = { 3846 },
            ["ITEM_126"] = { 3846 },
            -- Uncommon (w=28000)
            ["ITEM_128"] = { 1923 },
            ["ITEM_129"] = { 1923 },
            ["ITEM_130"] = { 1923 },
            ["ITEM_131"] = { 1923 },
            ["ITEM_132"] = { 1923 },
            ["ITEM_133"] = { 1923 },
            ["ITEM_134"] = { 1923 },
            ["ITEM_135"] = { 1923 },
            ["ITEM_136"] = { 1923 },
            ["ITEM_137"] = { 1923 },
            ["ITEM_138"] = { 1923 },
            ["ITEM_139"] = { 1923 },
            ["ITEM_140"] = { 1923 },
            -- Rare (w=15000)
            ["ITEM_142"] = { 962 },
            ["ITEM_143"] = { 962 },
            ["ITEM_144"] = { 962 },
            ["ITEM_145"] = { 962 },
            ["ITEM_146"] = { 962 },
            ["ITEM_147"] = { 962 },
            ["ITEM_148"] = { 962 },
            ["ITEM_149"] = { 962 },
            ["ITEM_150"] = { 962 },
            ["ITEM_151"] = { 962 },
            ["ITEM_152"] = { 962 },
            ["ITEM_153"] = { 962 },
            ["ITEM_154"] = { 962 },
            -- Epic (w=13000)
            ["ITEM_156"] = { 549 },
            ["ITEM_157"] = { 549 },
            ["ITEM_158"] = { 549 },
            ["ITEM_159"] = { 549 },
            ["ITEM_160"] = { 549 },
            ["ITEM_161"] = { 549 },
            ["ITEM_162"] = { 549 },
            ["ITEM_163"] = { 549 },
            ["ITEM_164"] = { 549 },
            ["ITEM_165"] = { 549 },
            ["ITEM_166"] = { 549 },
            ["ITEM_167"] = { 549 },
            ["ITEM_168"] = { 549 },
            -- Legendary (w=2000)
            ["ITEM_170"] = { 308 },
            ["ITEM_171"] = { 308 },
            ["ITEM_172"] = { 308 },
            ["ITEM_173"] = { 308 },
            ["ITEM_174"] = { 308 },
            ["ITEM_175"] = { 308 },
            ["ITEM_176"] = { 308 },
            ["ITEM_177"] = { 308 },
            ["ITEM_178"] = { 308 },
            ["ITEM_179"] = { 308 },
            ["ITEM_180"] = { 308 },
            ["ITEM_181"] = { 308 },
            ["ITEM_182"] = { 308 },
            -- Glitched (w=1200)
            ["ITEM_184"] = { 55 },
            ["ITEM_185"] = { 55 },
            ["ITEM_186"] = { 55 },
            ["ITEM_187"] = { 55 },
            ["ITEM_188"] = { 55 },
            ["ITEM_189"] = { 55 },
            ["ITEM_190"] = { 55 },
            ["ITEM_191"] = { 55 },
            ["ITEM_192"] = { 55 },
            ["ITEM_193"] = { 55 },
            ["ITEM_194"] = { 55 },
            ["ITEM_195"] = { 55 },
            ["ITEM_196"] = { 55 },
            -- Mythical (w=700)
            ["ITEM_198"] = { 31 },
            ["ITEM_199"] = { 31 },
            ["ITEM_200"] = { 31 },
            ["ITEM_201"] = { 31 },
            ["ITEM_202"] = { 31 },
            ["ITEM_203"] = { 31 },
            ["ITEM_204"] = { 31 },
            ["ITEM_205"] = { 31 },
            ["ITEM_206"] = { 31 },
            ["ITEM_207"] = { 31 },
            ["ITEM_208"] = { 31 },
            ["ITEM_209"] = { 31 },
            ["ITEM_210"] = { 31 },
        }
    },
    [3] = {
        Name = "Rifle Case", Model = 1, Rarity = "Common",
        Color = Color(42,133,219), Keys = { [3] = true },
        Items = {
            -- Common (w=40000)
            ["ITEM_211"] = { 2778 },
            ["ITEM_212"] = { 2778 },
            ["ITEM_213"] = { 2778 },
            ["ITEM_214"] = { 2778 },
            ["ITEM_215"] = { 2778 },
            ["ITEM_216"] = { 2778 },
            ["ITEM_217"] = { 2778 },
            ["ITEM_218"] = { 2778 },
            ["ITEM_219"] = { 2778 },
            ["ITEM_220"] = { 2778 },
            ["ITEM_221"] = { 2778 },
            ["ITEM_222"] = { 2778 },
            ["ITEM_223"] = { 2778 },
            ["ITEM_225"] = { 2778 },
            ["ITEM_226"] = { 2778 },
            ["ITEM_227"] = { 2778 },
            ["ITEM_228"] = { 2778 },
            ["ITEM_229"] = { 2778 },
            -- Uncommon (w=28000)
            ["ITEM_230"] = { 1389 },
            ["ITEM_231"] = { 1389 },
            ["ITEM_232"] = { 1389 },
            ["ITEM_233"] = { 1389 },
            ["ITEM_234"] = { 1389 },
            ["ITEM_235"] = { 1389 },
            ["ITEM_236"] = { 1389 },
            ["ITEM_237"] = { 1389 },
            ["ITEM_238"] = { 1389 },
            ["ITEM_239"] = { 1389 },
            ["ITEM_240"] = { 1389 },
            ["ITEM_241"] = { 1389 },
            ["ITEM_242"] = { 1389 },
            ["ITEM_244"] = { 1389 },
            ["ITEM_245"] = { 1389 },
            ["ITEM_246"] = { 1389 },
            ["ITEM_247"] = { 1389 },
            ["ITEM_248"] = { 1389 },
            -- Rare (w=15000)
            ["ITEM_249"] = { 694 },
            ["ITEM_250"] = { 694 },
            ["ITEM_251"] = { 694 },
            ["ITEM_252"] = { 694 },
            ["ITEM_253"] = { 694 },
            ["ITEM_254"] = { 694 },
            ["ITEM_255"] = { 694 },
            ["ITEM_256"] = { 694 },
            ["ITEM_257"] = { 694 },
            ["ITEM_258"] = { 694 },
            ["ITEM_259"] = { 694 },
            ["ITEM_260"] = { 694 },
            ["ITEM_261"] = { 694 },
            ["ITEM_263"] = { 694 },
            ["ITEM_264"] = { 694 },
            ["ITEM_265"] = { 694 },
            ["ITEM_266"] = { 694 },
            ["ITEM_267"] = { 694 },
            -- Epic (w=13000)
            ["ITEM_268"] = { 397 },
            ["ITEM_269"] = { 397 },
            ["ITEM_270"] = { 397 },
            ["ITEM_271"] = { 397 },
            ["ITEM_272"] = { 397 },
            ["ITEM_273"] = { 397 },
            ["ITEM_274"] = { 397 },
            ["ITEM_275"] = { 397 },
            ["ITEM_276"] = { 397 },
            ["ITEM_277"] = { 397 },
            ["ITEM_278"] = { 397 },
            ["ITEM_279"] = { 397 },
            ["ITEM_280"] = { 397 },
            ["ITEM_282"] = { 397 },
            ["ITEM_283"] = { 397 },
            ["ITEM_284"] = { 397 },
            ["ITEM_285"] = { 397 },
            ["ITEM_286"] = { 397 },
            -- Legendary (w=2000)
            ["ITEM_287"] = { 222 },
            ["ITEM_288"] = { 222 },
            ["ITEM_289"] = { 222 },
            ["ITEM_290"] = { 222 },
            ["ITEM_291"] = { 222 },
            ["ITEM_292"] = { 222 },
            ["ITEM_293"] = { 222 },
            ["ITEM_294"] = { 222 },
            ["ITEM_295"] = { 222 },
            ["ITEM_296"] = { 222 },
            ["ITEM_297"] = { 222 },
            ["ITEM_298"] = { 222 },
            ["ITEM_299"] = { 222 },
            ["ITEM_301"] = { 222 },
            ["ITEM_302"] = { 222 },
            ["ITEM_303"] = { 222 },
            ["ITEM_304"] = { 222 },
            ["ITEM_305"] = { 222 },
            -- Glitched (w=1200)
            ["ITEM_306"] = { 40 },
            ["ITEM_307"] = { 40 },
            ["ITEM_308"] = { 40 },
            ["ITEM_309"] = { 40 },
            ["ITEM_310"] = { 40 },
            ["ITEM_311"] = { 40 },
            ["ITEM_312"] = { 40 },
            ["ITEM_313"] = { 40 },
            ["ITEM_314"] = { 40 },
            ["ITEM_315"] = { 40 },
            ["ITEM_316"] = { 40 },
            ["ITEM_317"] = { 40 },
            ["ITEM_318"] = { 40 },
            ["ITEM_320"] = { 40 },
            ["ITEM_321"] = { 40 },
            ["ITEM_322"] = { 40 },
            ["ITEM_323"] = { 40 },
            ["ITEM_324"] = { 40 },
            -- Mythical (w=700)
            ["ITEM_325"] = { 22 },
            ["ITEM_326"] = { 22 },
            ["ITEM_327"] = { 22 },
            ["ITEM_328"] = { 22 },
            ["ITEM_329"] = { 22 },
            ["ITEM_330"] = { 22 },
            ["ITEM_331"] = { 22 },
            ["ITEM_332"] = { 22 },
            ["ITEM_333"] = { 22 },
            ["ITEM_334"] = { 22 },
            ["ITEM_335"] = { 22 },
            ["ITEM_336"] = { 22 },
            ["ITEM_337"] = { 22 },
            ["ITEM_339"] = { 22 },
            ["ITEM_340"] = { 22 },
            ["ITEM_341"] = { 22 },
            ["ITEM_342"] = { 22 },
            ["ITEM_343"] = { 22 },
        }
    },
    [4] = {
        Name = "Shotgun Case", Model = 1, Rarity = "Common",
        Color = Color(255,165,0), Keys = { [4] = true },
        Items = {
            -- Common (w=40000)
            ["ITEM_344"] = { 5000 },
            ["ITEM_345"] = { 5000 },
            ["ITEM_346"] = { 5000 },
            ["ITEM_347"] = { 5000 },
            ["ITEM_348"] = { 5000 },
            ["ITEM_349"] = { 5000 },
            ["ITEM_351"] = { 5000 },
            ["ITEM_352"] = { 5000 },
            ["ITEM_353"] = { 5000 },
            ["ITEM_354"] = { 5000 },
            -- Uncommon (w=28000)
            ["ITEM_355"] = { 2500 },
            ["ITEM_356"] = { 2500 },
            ["ITEM_357"] = { 2500 },
            ["ITEM_358"] = { 2500 },
            ["ITEM_359"] = { 2500 },
            ["ITEM_360"] = { 2500 },
            ["ITEM_362"] = { 2500 },
            ["ITEM_363"] = { 2500 },
            ["ITEM_364"] = { 2500 },
            ["ITEM_365"] = { 2500 },
            -- Rare (w=15000)
            ["ITEM_366"] = { 1250 },
            ["ITEM_367"] = { 1250 },
            ["ITEM_368"] = { 1250 },
            ["ITEM_369"] = { 1250 },
            ["ITEM_370"] = { 1250 },
            ["ITEM_371"] = { 1250 },
            ["ITEM_373"] = { 1250 },
            ["ITEM_374"] = { 1250 },
            ["ITEM_375"] = { 1250 },
            ["ITEM_376"] = { 1250 },
            -- Epic (w=13000)
            ["ITEM_377"] = { 714 },
            ["ITEM_378"] = { 714 },
            ["ITEM_379"] = { 714 },
            ["ITEM_380"] = { 714 },
            ["ITEM_381"] = { 714 },
            ["ITEM_382"] = { 714 },
            ["ITEM_384"] = { 714 },
            ["ITEM_385"] = { 714 },
            ["ITEM_386"] = { 714 },
            ["ITEM_387"] = { 714 },
            -- Legendary (w=2000)
            ["ITEM_388"] = { 400 },
            ["ITEM_389"] = { 400 },
            ["ITEM_390"] = { 400 },
            ["ITEM_391"] = { 400 },
            ["ITEM_392"] = { 400 },
            ["ITEM_393"] = { 400 },
            ["ITEM_395"] = { 400 },
            ["ITEM_396"] = { 400 },
            ["ITEM_397"] = { 400 },
            ["ITEM_398"] = { 400 },
            -- Glitched (w=1200)
            ["ITEM_399"] = { 71 },
            ["ITEM_400"] = { 71 },
            ["ITEM_401"] = { 71 },
            ["ITEM_402"] = { 71 },
            ["ITEM_403"] = { 71 },
            ["ITEM_404"] = { 71 },
            ["ITEM_406"] = { 71 },
            ["ITEM_407"] = { 71 },
            ["ITEM_408"] = { 71 },
            ["ITEM_409"] = { 71 },
            -- Mythical (w=700)
            ["ITEM_410"] = { 40 },
            ["ITEM_411"] = { 40 },
            ["ITEM_412"] = { 40 },
            ["ITEM_413"] = { 40 },
            ["ITEM_414"] = { 40 },
            ["ITEM_415"] = { 40 },
            ["ITEM_417"] = { 40 },
            ["ITEM_418"] = { 40 },
            ["ITEM_419"] = { 40 },
            ["ITEM_420"] = { 40 },
        }
    },
    [5] = {
        Name = "Sniper Case", Model = 1, Rarity = "Common",
        Color = Color(152,68,255), Keys = { [5] = true },
        Items = {
            -- Common (w=40000)
            ["ITEM_421"] = { 4545 },
            ["ITEM_422"] = { 4545 },
            ["ITEM_423"] = { 4545 },
            ["ITEM_424"] = { 4545 },
            ["ITEM_425"] = { 4545 },
            ["ITEM_426"] = { 4545 },
            ["ITEM_427"] = { 4545 },
            ["ITEM_428"] = { 4545 },
            ["ITEM_429"] = { 4545 },
            ["ITEM_430"] = { 4545 },
            ["ITEM_431"] = { 4545 },
            -- Uncommon (w=28000)
            ["ITEM_432"] = { 2273 },
            ["ITEM_433"] = { 2273 },
            ["ITEM_434"] = { 2273 },
            ["ITEM_435"] = { 2273 },
            ["ITEM_436"] = { 2273 },
            ["ITEM_437"] = { 2273 },
            ["ITEM_438"] = { 2273 },
            ["ITEM_439"] = { 2273 },
            ["ITEM_440"] = { 2273 },
            ["ITEM_441"] = { 2273 },
            ["ITEM_442"] = { 2273 },
            -- Rare (w=15000)
            ["ITEM_443"] = { 1136 },
            ["ITEM_444"] = { 1136 },
            ["ITEM_445"] = { 1136 },
            ["ITEM_446"] = { 1136 },
            ["ITEM_447"] = { 1136 },
            ["ITEM_448"] = { 1136 },
            ["ITEM_449"] = { 1136 },
            ["ITEM_450"] = { 1136 },
            ["ITEM_451"] = { 1136 },
            ["ITEM_452"] = { 1136 },
            ["ITEM_453"] = { 1136 },
            -- Epic (w=13000)
            ["ITEM_454"] = { 649 },
            ["ITEM_455"] = { 649 },
            ["ITEM_456"] = { 649 },
            ["ITEM_457"] = { 649 },
            ["ITEM_458"] = { 649 },
            ["ITEM_459"] = { 649 },
            ["ITEM_460"] = { 649 },
            ["ITEM_461"] = { 649 },
            ["ITEM_462"] = { 649 },
            ["ITEM_463"] = { 649 },
            ["ITEM_464"] = { 649 },
            -- Legendary (w=2000)
            ["ITEM_465"] = { 364 },
            ["ITEM_466"] = { 364 },
            ["ITEM_467"] = { 364 },
            ["ITEM_468"] = { 364 },
            ["ITEM_469"] = { 364 },
            ["ITEM_470"] = { 364 },
            ["ITEM_471"] = { 364 },
            ["ITEM_472"] = { 364 },
            ["ITEM_473"] = { 364 },
            ["ITEM_474"] = { 364 },
            ["ITEM_475"] = { 364 },
            -- Glitched (w=1200)
            ["ITEM_476"] = { 65 },
            ["ITEM_477"] = { 65 },
            ["ITEM_478"] = { 65 },
            ["ITEM_479"] = { 65 },
            ["ITEM_480"] = { 65 },
            ["ITEM_481"] = { 65 },
            ["ITEM_482"] = { 65 },
            ["ITEM_483"] = { 65 },
            ["ITEM_484"] = { 65 },
            ["ITEM_485"] = { 65 },
            ["ITEM_486"] = { 65 },
            -- Mythical (w=700)
            ["ITEM_487"] = { 36 },
            ["ITEM_488"] = { 36 },
            ["ITEM_489"] = { 36 },
            ["ITEM_490"] = { 36 },
            ["ITEM_491"] = { 36 },
            ["ITEM_492"] = { 36 },
            ["ITEM_493"] = { 36 },
            ["ITEM_494"] = { 36 },
            ["ITEM_495"] = { 36 },
            ["ITEM_496"] = { 36 },
            ["ITEM_497"] = { 36 },
        }
    },
    [6] = {
        Name = "Heavy Case", Model = 1, Rarity = "Common",
        Color = Color(255,50,50), Keys = { [6] = true },
        Items = {
            -- Common (w=40000)
            ["ITEM_498"] = { 7143 },
            ["ITEM_499"] = { 7143 },
            ["ITEM_500"] = { 7143 },
            ["ITEM_501"] = { 7143 },
            ["ITEM_502"] = { 7143 },
            ["ITEM_503"] = { 7143 },
            ["ITEM_504"] = { 7143 },
            -- Uncommon (w=28000)
            ["ITEM_505"] = { 3571 },
            ["ITEM_506"] = { 3571 },
            ["ITEM_507"] = { 3571 },
            ["ITEM_508"] = { 3571 },
            ["ITEM_509"] = { 3571 },
            ["ITEM_510"] = { 3571 },
            ["ITEM_511"] = { 3571 },
            -- Rare (w=15000)
            ["ITEM_512"] = { 1786 },
            ["ITEM_513"] = { 1786 },
            ["ITEM_514"] = { 1786 },
            ["ITEM_515"] = { 1786 },
            ["ITEM_516"] = { 1786 },
            ["ITEM_517"] = { 1786 },
            ["ITEM_518"] = { 1786 },
            -- Epic (w=13000)
            ["ITEM_519"] = { 1020 },
            ["ITEM_520"] = { 1020 },
            ["ITEM_521"] = { 1020 },
            ["ITEM_522"] = { 1020 },
            ["ITEM_523"] = { 1020 },
            ["ITEM_524"] = { 1020 },
            ["ITEM_525"] = { 1020 },
            -- Legendary (w=2000)
            ["ITEM_526"] = { 571 },
            ["ITEM_527"] = { 571 },
            ["ITEM_528"] = { 571 },
            ["ITEM_529"] = { 571 },
            ["ITEM_530"] = { 571 },
            ["ITEM_531"] = { 571 },
            ["ITEM_532"] = { 571 },
            -- Glitched (w=1200)
            ["ITEM_533"] = { 102 },
            ["ITEM_534"] = { 102 },
            ["ITEM_535"] = { 102 },
            ["ITEM_536"] = { 102 },
            ["ITEM_537"] = { 102 },
            ["ITEM_538"] = { 102 },
            ["ITEM_539"] = { 102 },
            -- Mythical (w=700)
            ["ITEM_540"] = { 57 },
            ["ITEM_541"] = { 57 },
            ["ITEM_542"] = { 57 },
            ["ITEM_543"] = { 57 },
            ["ITEM_544"] = { 57 },
            ["ITEM_545"] = { 57 },
            ["ITEM_546"] = { 57 },
        }
    },
}

-- ============================================================
-- 6 KEYS
-- ============================================================
BRICKS_SERVER.BASECONFIG.UNBOXING.Keys = {
    [1] = { Name = "Pistol Key", Model = 1, Rarity = "Common", Color = Color(200,200,200) },
    [2] = { Name = "SMG Key", Model = 1, Rarity = "Uncommon", Color = Color(130,255,130) },
    [3] = { Name = "Rifle Key", Model = 1, Rarity = "Rare", Color = Color(80,180,255) },
    [4] = { Name = "Shotgun Key", Model = 1, Rarity = "Epic", Color = Color(255,190,80) },
    [5] = { Name = "Sniper Key", Model = 1, Rarity = "Legendary", Color = Color(180,100,255) },
    [6] = { Name = "Heavy Key", Model = 1, Rarity = "Glitched", Color = Color(255,80,80) },
}

-- ============================================================
-- STORE
-- ============================================================
BRICKS_SERVER.BASECONFIG.UNBOXING.Store = BRICKS_SERVER.BASECONFIG.UNBOXING.Store or {}
BRICKS_SERVER.BASECONFIG.UNBOXING.Store.Featured = BRICKS_SERVER.BASECONFIG.UNBOXING.Store.Featured or {}
BRICKS_SERVER.BASECONFIG.UNBOXING.Store.Categories = BRICKS_SERVER.BASECONFIG.UNBOXING.Store.Categories or {
    [1] = { Name = "Weapons", SortOrder = 1 },
    [2] = { Name = "Cases", SortOrder = 2 },
    [3] = { Name = "Keys", SortOrder = 3 },
}
BRICKS_SERVER.BASECONFIG.UNBOXING.Store.Items = BRICKS_SERVER.BASECONFIG.UNBOXING.Store.Items or {
    [1] = { GlobalKey = "CASE_1", Category = 2, SortOrder = 1, Price = 2000 },
    [2] = { GlobalKey = "CASE_2", Category = 2, SortOrder = 2, Price = 3000 },
    [3] = { GlobalKey = "CASE_3", Category = 2, SortOrder = 3, Price = 5000 },
    [4] = { GlobalKey = "CASE_4", Category = 2, SortOrder = 4, Price = 5000 },
    [5] = { GlobalKey = "CASE_5", Category = 2, SortOrder = 5, Price = 7500 },
    [6] = { GlobalKey = "CASE_6", Category = 2, SortOrder = 6, Price = 10000 },
    [7] = { GlobalKey = "KEY_1", Category = 3, SortOrder = 1, Price = 1000 },
    [8] = { GlobalKey = "KEY_2", Category = 3, SortOrder = 2, Price = 1500 },
    [9] = { GlobalKey = "KEY_3", Category = 3, SortOrder = 3, Price = 2500 },
    [10] = { GlobalKey = "KEY_4", Category = 3, SortOrder = 4, Price = 2500 },
    [11] = { GlobalKey = "KEY_5", Category = 3, SortOrder = 5, Price = 3750 },
    [12] = { GlobalKey = "KEY_6", Category = 3, SortOrder = 6, Price = 5000 },
}

-- ============================================================
-- MARKETPLACE
-- ============================================================
BRICKS_SERVER.BASECONFIG.UNBOXING.Marketplace = BRICKS_SERVER.BASECONFIG.UNBOXING.Marketplace or {}
BRICKS_SERVER.BASECONFIG.UNBOXING.Marketplace.Slots = BRICKS_SERVER.BASECONFIG.UNBOXING.Marketplace.Slots or {
    [1] = {},
}

-- ============================================================
-- REWARDS (daily login rewards)
-- ============================================================
BRICKS_SERVER.BASECONFIG.UNBOXING.Rewards = BRICKS_SERVER.BASECONFIG.UNBOXING.Rewards or {
    [1] = { GlobalKey = "KEY_1", Amount = 1 },
    [2] = { GlobalKey = "KEY_2", Amount = 1 },
    [3] = { GlobalKey = "KEY_3", Amount = 1 },
    [4] = { GlobalKey = "CASE_1", Amount = 1 },
    [5] = { GlobalKey = "KEY_4", Amount = 1 },
    [6] = { GlobalKey = "KEY_5", Amount = 1 },
    [7] = { GlobalKey = "CASE_3", Amount = 1 },
}

-- ============================================================
-- NOTIFICATION RARITIES (announce to server)
-- ============================================================
BRICKS_SERVER.BASECONFIG.UNBOXING.NotificationRarities = BRICKS_SERVER.BASECONFIG.UNBOXING.NotificationRarities or {
    ["Rare"] = true,
    ["Epic"] = true,
    ["Legendary"] = true,
    ["Glitched"] = true,
    ["Mythical"] = true,
}

-- ============================================================
-- DROPS (timed random drops while playing)
-- ============================================================
BRICKS_SERVER.BASECONFIG.UNBOXING.Drops = BRICKS_SERVER.BASECONFIG.UNBOXING.Drops or {}
BRICKS_SERVER.BASECONFIG.UNBOXING.Drops.TimeInterval = BRICKS_SERVER.BASECONFIG.UNBOXING.Drops.TimeInterval or 900
BRICKS_SERVER.BASECONFIG.UNBOXING.Drops.Items = BRICKS_SERVER.BASECONFIG.UNBOXING.Drops.Items or {
    [1] = { "CASE_1", 30 },
    [2] = { "CASE_2", 25 },
    [3] = { "CASE_3", 20 },
    [4] = { "CASE_4", 20 },
    [5] = { "CASE_5", 15 },
    [6] = { "CASE_6", 10 },
}

-- ============================================================
-- NPCS
-- ============================================================
BRICKS_SERVER.BASECONFIG.NPCS = BRICKS_SERVER.BASECONFIG.NPCS or {}

local hasUnboxingNPC = false
for _, npcData in ipairs(BRICKS_SERVER.BASECONFIG.NPCS) do
    if istable(npcData) and npcData.Type == "Unboxing" then
        hasUnboxingNPC = true
        break
    end
end
if not hasUnboxingNPC then
    table.insert(BRICKS_SERVER.BASECONFIG.NPCS, {
        Name = "Unboxing",
        Type = "Unboxing",
    })
end
